features:
  - "count_purchase"
  - "ctr"

target: "CartUpdate_vs_View"

data:
  train_path: "train.parquet"
  test_path: "test.parquet"
  sample_size: null  # null means use all data
  random_seed: 42

preprocessing:
  normalize_timestamps: true
  clean_text: false

history_cleaning:
  remove_lurkers: false

history_generation:
  method: "basic"  # "basic" or "rolling_window"
  rolling_window:
    window_size: 30
  final_ratio: 0.2  # amount of data to use for feature generation during final training

model:
  type: "catboost"  # "catboost", "lightgbm", "xgboost", or "random_forest"
  config:
    catboost:
      iterations: 300
      learning_rate: 0.01
      depth: 2
      loss_function: "Logloss"
      eval_metric: "AUC"
      early_stopping_rounds: 50
    lightgbm:
      num_iterations: 500
      learning_rate: 0.05
      max_depth: 6
      objective: "binary"
      metric: "auc"
      early_stopping_rounds: 50
      verbose: 100
    xgboost:
      n_estimators: 500
      learning_rate: 0.05
      max_depth: 6
      objective: "binary:logistic"
      eval_metric: "auc"
      early_stopping_rounds: 50
      verbose: 100
    random_forest:
      n_estimators: 100
      max_depth: 10
      min_samples_split: 2
      random_state: 42

# Add this to your default_config.yaml file

validation:
  method: "temporal"  # Options: temporal, temporal_classic
  n_folds: 3
  time_window_days: 7  # Size of validation window in days

history_generation:
  method: "time_window"  # Options: basic, sliding_window, all_history, time_window
  window_days: 30  # Window size for sliding_window method
  recent_window_days: 7  # Recent window size for time_window method
  mid_window_days: 30  # Mid-term window size for time_window method
  long_window_days: 90  # Long-term window size for time_window method
  final_ratio: 0.2  # Ratio for final model training (only used if not time-based)
  use_time_based_final: true  # Whether to use time-based split for final model
  final_days_for_test: 7  # Days to use for test in final model training

metrics:
  - "auc"
  - "ndcg@10"
  - "map@10"
  - "novelty@10"
  - "serendipity@10"

output:
  results_dir: "results"
  save_model: true
  save_predictions: true
